#version: '3.8'
#services:
#  app:
#    image: tutorial-app
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    depends_on:
#      - db
#      - redis
#
#  db:
#    image: postgres:14
#    container_name: postgres-db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: postgres
#    ports:
#      - "5432:5432"
#
#  redis:
#    image: redis:7
#    container_name: redis-server
#    ports:
#      - "6379:6379"
